version: '2'

services:
  elasticsearch:
    container_name: elasticsearch_esio
    image: elasticsearch:1.7
    volumes:
      - "./elasticDump/data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
  esio:
    container_name: esio
    build: ./
    volumes:
     - ./cmd/:/go/src/esio/cmd/
     - ./models/:/go/src/esio/models/
     - ./restapi/:/go/src/esio/restapi/
    ports:
      - "8000:8000"
    environment:
      - ACCESSKEY=REPLACE_WITH_REAL_KEY
      - SECRETKEY=REPLACE_WITH_REAL_KEY